/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface LanguageDefinition {
  id: string;
  name: string;
  category: 'Popular' | 'Systems' | 'Web' | 'Data & Scripting';
  extension: string;
  defaultFilename: string;
  color: string;
  badgeBg: string;
  badgeBorder: string;
  starterCode: string;
  aiSnippet: {
    label: string;
    description: string;
    code: string;
  };
  pasteSnippet: {
    label: string;
    description: string;
    code: string;
  };
}

export const SUPPORTED_LANGUAGES: LanguageDefinition[] = [
  {
    id: 'python',
    name: 'Python',
    category: 'Popular',
    extension: '.py',
    defaultFilename: 'main.py',
    color: '#3776ab',
    badgeBg: 'bg-blue-500/20 text-blue-300',
    badgeBorder: 'border-blue-500/30',
    starterCode: `def main():
    print("Python environment ready.")

if __name__ == "__main__":
    main()`,
    aiSnippet: {
      label: 'FastAPI Telemetry Validator',
      description: 'Pydantic model and async endpoint generated by Copilot',
      code: `from pydantic import BaseModel, Field
from typing import Optional

class ProvenancePayload(BaseModel):
    repository: str
    commit_sha: str = Field(..., min_length=7, max_length=40)
    ai_percentage: float = Field(..., ge=0.0, le=100.0)
    typed_percentage: float = Field(..., ge=0.0, le=100.0)
    is_sealed: bool = True

async def verify_ci_gate(payload: ProvenancePayload) -> bool:
    if payload.ai_percentage > 50.0:
        raise ValueError(f"AI ratio {payload.ai_percentage}% exceeds policy threshold")
    return payload.typed_percentage >= 20.0`
    },
    pasteSnippet: {
      label: 'StackOverflow Memoized Decorator',
      description: 'Copied from Python StackOverflow thread #19888',
      code: `# Pasted snippet: functools LRU cache implementation
def memoize(func):
    cache = {}
    def wrapper(*args):
        if args not in cache:
            cache[args] = func(*args)
        return cache[args]
    return wrapper`
    }
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'Popular',
    extension: '.ts',
    defaultFilename: 'index.ts',
    color: '#3178c6',
    badgeBg: 'bg-sky-500/20 text-sky-300',
    badgeBorder: 'border-sky-500/30',
    starterCode: `export interface AppState {
  version: string;
  active: boolean;
}

export function initialize(): AppState {
  return { version: "1.0.0", active: true };
}`,
    aiSnippet: {
      label: 'Async Generic Binary Search Tree',
      description: 'Type-safe balanced tree traversal generated by Copilot',
      code: `export class TreeNode<T> {
  value: T;
  left: TreeNode<T> | null = null;
  right: TreeNode<T> | null = null;

  constructor(value: T) {
    this.value = value;
  }

  insert(newValue: T, compare: (a: T, b: T) => number): void {
    if (compare(newValue, this.value) < 0) {
      if (this.left) this.left.insert(newValue, compare);
      else this.left = new TreeNode(newValue);
    } else {
      if (this.right) this.right.insert(newValue, compare);
      else this.right = new TreeNode(newValue);
    }
  }
}`
    },
    pasteSnippet: {
      label: 'StackOverflow Email RFC Regex',
      description: 'Copied from StackOverflow validator snippet',
      code: `// Pasted RFC-compliant email regex
const RFC_EMAIL = /^[a-zA-Z0-9.!#$%&'*+/=?^_\`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;`
    }
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    category: 'Web',
    extension: '.js',
    defaultFilename: 'app.js',
    color: '#f7df1e',
    badgeBg: 'bg-yellow-500/20 text-yellow-300',
    badgeBorder: 'border-yellow-500/30',
    starterCode: `export function initApp() {
  console.log("JavaScript environment ready.");
  return { status: "ready" };
}`,
    aiSnippet: {
      label: 'Promise Concurrency Pool',
      description: 'Generated async throttle scheduler',
      code: `async function pMap(items, mapper, concurrency = 4) {
  const results = [];
  const executing = new Set();
  for (const item of items) {
    const p = Promise.resolve().then(() => mapper(item));
    results.push(p);
    executing.add(p);
    const clean = () => executing.delete(p);
    p.then(clean).catch(clean);
    if (executing.size >= concurrency) {
      await Promise.race(executing);
    }
  }
  return Promise.all(results);
}`
    },
    pasteSnippet: {
      label: 'StackOverflow Deep Clone',
      description: 'Copied deep clone function without structuredClone',
      code: `function deepClone(obj, hash = new WeakMap()) {
  if (Object(obj) !== obj || obj instanceof Function) return obj;
  if (hash.has(obj)) return hash.get(obj);
  const result = Array.isArray(obj) ? [] : {};
  hash.set(obj, result);
  return Object.assign(result, ...Object.keys(obj).map(key => ({ [key]: deepClone(obj[key], hash) })));
}`
    }
  },
  {
    id: 'rust',
    name: 'Rust',
    category: 'Systems',
    extension: '.rs',
    defaultFilename: 'main.rs',
    color: '#dea584',
    badgeBg: 'bg-orange-500/20 text-orange-300',
    badgeBorder: 'border-orange-500/30',
    starterCode: `fn main() {
    println!("Rust environment ready.");
}`,
    aiSnippet: {
      label: 'Sha256 Merkle Link Struct',
      description: 'Memory-safe cryptographic block link generated by Copilot',
      code: `use std::fmt;

pub struct CryptographicLink {
    pub sequence: u64,
    pub prev_hash: [u8; 32],
    pub current_hash: [u8; 32],
}

impl CryptographicLink {
    pub fn new_genesis() -> Self {
        Self {
            sequence: 0,
            prev_hash: [0u8; 32],
            current_hash: [0x5a; 32],
        }
    }

    pub fn verify_continuity(&self, previous: &CryptographicLink) -> bool {
        self.sequence == previous.sequence + 1 && self.prev_hash == previous.current_hash
    }
}`
    },
    pasteSnippet: {
      label: 'StackOverflow FNV-1a Hash',
      description: 'Pasted pure Rust fast hashing algorithm',
      code: `// Pasted from Rust cookbook
pub fn fnv1a_hash(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf29ce484222325u64;
    for &byte in bytes {
        hash ^= byte as u64;
        hash = hash.wrapping_mul(0x100000001b3u64);
    }
    hash
}`
    }
  },
  {
    id: 'go',
    name: 'Go',
    category: 'Systems',
    extension: '.go',
    defaultFilename: 'main.go',
    color: '#00add8',
    badgeBg: 'bg-cyan-500/20 text-cyan-300',
    badgeBorder: 'border-cyan-500/30',
    starterCode: `package main

import "fmt"

func main() {
	fmt.Println("Go environment ready.")
}`,
    aiSnippet: {
      label: 'Worker Pool with Channels',
      description: 'Concurrent audit processing generated by Copilot',
      code: `package main

import "sync"

type Job struct {
	LineID int
	Text   string
}

func ProcessAudits(jobs <-chan Job, results chan<- bool, wg *sync.WaitGroup) {
	defer wg.Done()
	for job := range jobs {
		// Heuristic classification logic
		isValid := len(job.Text) > 0
		results <- isValid
	}
}`
    },
    pasteSnippet: {
      label: 'StackOverflow HTTP Retry Wrapper',
      description: 'Copied Go exponential backoff snippet',
      code: `// Pasted exponential backoff
func Retry(attempts int, sleep time.Duration, fn func() error) error {
	if err := fn(); err != nil {
		if attempts--; attempts > 0 {
			time.Sleep(sleep)
			return Retry(attempts, 2*sleep, fn)
		}
		return err
	}
	return nil
}`
    }
  },
  {
    id: 'java',
    name: 'Java',
    category: 'Popular',
    extension: '.java',
    defaultFilename: 'Main.java',
    color: '#b07219',
    badgeBg: 'bg-amber-500/20 text-amber-300',
    badgeBorder: 'border-amber-500/30',
    starterCode: `public class Main {
    public static void main(String[] args) {
        System.out.println("Java environment ready.");
    }
}`,
    aiSnippet: {
      label: 'Spring Security Token Filter',
      description: 'Copilot generated JWT bearer validator',
      code: `import java.security.MessageDigest;
import java.nio.charset.StandardCharsets;

public class ProvenanceAttestation {
    public static String computeDigest(String payload) throws Exception {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        byte[] hash = digest.digest(payload.getBytes(StandardCharsets.UTF_8));
        StringBuilder hexString = new StringBuilder();
        for (byte b : hash) {
            String hex = Integer.toHexString(0xff & b);
            if (hex.length() == 1) hexString.append('0');
            hexString.append(hex);
        }
        return hexString.toString();
    }
}`
    },
    pasteSnippet: {
      label: 'StackOverflow Levenshtein Distance',
      description: 'Copied string edit distance algorithm',
      code: `// Pasted Levenshtein implementation
public static int levenshtein(String a, String b) {
    int[] costs = new int[b.length() + 1];
    for (int j = 0; j < costs.length; j++) costs[j] = j;
    for (int i = 1; i <= a.length(); i++) {
        costs[0] = i;
        int nw = i - 1;
        for (int j = 1; j <= b.length(); j++) {
            int cj = Math.min(1 + Math.min(costs[j], costs[j - 1]), a.charAt(i - 1) == b.charAt(j - 1) ? nw : nw + 1);
            nw = costs[j];
            costs[j] = cj;
        }
    }
    return costs[b.length()];
}`
    }
  },
  {
    id: 'cpp',
    name: 'C++',
    category: 'Systems',
    extension: '.cpp',
    defaultFilename: 'main.cpp',
    color: '#f34b7d',
    badgeBg: 'bg-rose-500/20 text-rose-300',
    badgeBorder: 'border-rose-500/30',
    starterCode: `#include <iostream>

int main() {
    std::cout << "C++ environment ready." << std::endl;
    return 0;
}`,
    aiSnippet: {
      label: 'Template Circular Buffer',
      description: 'Modern C++20 thread-safe buffer generated by Copilot',
      code: `template <typename T, std::size_t Capacity>
class CircularBuffer {
    T data[Capacity];
    std::size_t head = 0;
    std::size_t tail = 0;
    bool is_full = false;

public:
    void push(T item) {
        data[head] = item;
        if (is_full) tail = (tail + 1) % Capacity;
        head = (head + 1) % Capacity;
        is_full = head == tail;
    }
};`
    },
    pasteSnippet: {
      label: 'StackOverflow Fast Hex Converter',
      description: 'Pasted C++ byte array to hex string function',
      code: `// Pasted fast byte-to-hex
std::string to_hex(const unsigned char* data, size_t len) {
    static const char hex_digits[] = "0123456789abcdef";
    std::string output;
    output.reserve(len * 2);
    for (size_t i = 0; i < len; ++i) {
        output.push_back(hex_digits[(data[i] >> 4) & 0x0F]);
        output.push_back(hex_digits[data[i] & 0x0F]);
    }
    return output;
}`
    }
  },
  {
    id: 'csharp',
    name: 'C#',
    category: 'Popular',
    extension: '.cs',
    defaultFilename: 'Program.cs',
    color: '#178600',
    badgeBg: 'bg-emerald-500/20 text-emerald-300',
    badgeBorder: 'border-emerald-500/30',
    starterCode: `using System;

namespace App;

public class Program 
{
    public static void Main() 
    {
        Console.WriteLine("C# environment ready.");
    }
}`,
    aiSnippet: {
      label: 'LINQ Query Policy Evaluator',
      description: 'Copilot generated policy validator',
      code: `public static class PolicyGate
{
    public static bool Evaluate(IEnumerable<CodeLine> lines, int maxAiPct)
    {
        var total = lines.Count();
        if (total == 0) return true;
        var aiCount = lines.Count(l => l.Origin == "ai");
        var actualPct = (double)aiCount / total * 100;
        return actualPct <= maxAiPct;
    }
}`
    },
    pasteSnippet: {
      label: 'StackOverflow ThreadSafe Singleton',
      description: 'Pasted lazy initialization pattern',
      code: `// Pasted Thread-safe Lazy Singleton
public sealed class TelemetryService
{
    private static readonly Lazy<TelemetryService> lazy =
        new Lazy<TelemetryService>(() => new TelemetryService());

    public static TelemetryService Instance => lazy.Value;
    private TelemetryService() { }
}`
    }
  },
  {
    id: 'ruby',
    name: 'Ruby',
    category: 'Data & Scripting',
    extension: '.rb',
    defaultFilename: 'app.rb',
    color: '#701516',
    badgeBg: 'bg-red-500/20 text-red-300',
    badgeBorder: 'border-red-500/30',
    starterCode: `def run_app
  puts "Ruby environment ready."
end

run_app`,
    aiSnippet: {
      label: 'Rack Middleware Inspector',
      description: 'Copilot generated provenance header checker',
      code: `class ProvenanceInspector
  def initialize(app, policy)
    @app = app
    @policy = policy
  end

  def call(env)
    status, headers, response = @app.call(env)
    headers['X-Provenance-Audited'] = 'true'
    [status, headers, response]
  end
end`
    },
    pasteSnippet: {
      label: 'StackOverflow Nested Hash Fetch',
      description: 'Pasted deep fetch utility',
      code: `# Pasted safe nested hash traversal
def deep_find(hash, key)
  return hash[key] if hash.key?(key)
  hash.each do |k, v|
    if v.is_a?(Hash)
      res = deep_find(v, key)
      return res if res
    end
  end
  nil
end`
    }
  },
  {
    id: 'php',
    name: 'PHP',
    category: 'Web',
    extension: '.php',
    defaultFilename: 'index.php',
    color: '#4f5d95',
    badgeBg: 'bg-indigo-500/20 text-indigo-300',
    badgeBorder: 'border-indigo-500/30',
    starterCode: `<?php
declare(strict_types=1);

echo "PHP environment ready.\\n";`,
    aiSnippet: {
      label: 'PHP 8.2 Attestation Validator',
      description: 'Copilot generated typed validator class',
      code: `readonly class BundleValidator {
    public function __construct(
        private int $maxAiPercentage = 50,
        private int $minTypedPercentage = 20
    ) {}

    public function validate(array $summary): bool {
        $aiPct = $summary['percentages']['ai'] ?? 0;
        $typedPct = $summary['percentages']['typed'] ?? 0;
        return $aiPct <= $this->maxAiPercentage && $typedPct >= $this->minTypedPercentage;
    }
}`
    },
    pasteSnippet: {
      label: 'StackOverflow Sanitizer Helper',
      description: 'Pasted input sanitizer snippet',
      code: `// Pasted array XSS cleaner
function cleanInput(array $data): array {
    return array_map(function($value) {
        return is_array($value) ? cleanInput($value) : htmlspecialchars(trim((string)$value), ENT_QUOTES, 'UTF-8');
    }, $data);
}`
    }
  },
  {
    id: 'swift',
    name: 'Swift',
    category: 'Systems',
    extension: '.swift',
    defaultFilename: 'Main.swift',
    color: '#f05138',
    badgeBg: 'bg-rose-500/20 text-rose-300',
    badgeBorder: 'border-rose-500/30',
    starterCode: `import Foundation

func startApp() {
    print("Swift environment ready.")
}

startApp()`,
    aiSnippet: {
      label: 'Swift Actor for Thread-Safe Ledger',
      description: 'Copilot generated async actor store',
      code: `actor ProvenanceLedger {
    private var events: [String] = []

    func appendEvent(_ hash: String) {
        events.append(hash)
    }

    func currentCount() -> Int {
        return events.count
    }
}`
    },
    pasteSnippet: {
      label: 'StackOverflow URL Query Parser',
      description: 'Pasted URL components query extractor',
      code: `// Pasted URL query params dictionary extractor
extension URL {
    var queryParameters: [String: String]? {
        guard let components = URLComponents(url: self, resolvingAgainstBaseURL: true),
              let queryItems = components.queryItems else { return nil }
        return queryItems.reduce(into: [String: String]()) { result, item in
            result[item.name] = item.value
        }
    }
}`
    }
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    category: 'Popular',
    extension: '.kt',
    defaultFilename: 'Main.kt',
    color: '#a97bff',
    badgeBg: 'bg-purple-500/20 text-purple-300',
    badgeBorder: 'border-purple-500/30',
    starterCode: `fun main() {
    println("Kotlin environment ready.")
}`,
    aiSnippet: {
      label: 'Coroutines Flow Event Pipeline',
      description: 'Copilot generated reactive event stream',
      code: `import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

fun auditStream(events: List<ProvenanceEntry>): Flow<String> = flow {
    for (event in events) {
        emit("Audited link for line \${event.line} with origin \${event.origin}")
    }
}`
    },
    pasteSnippet: {
      label: 'StackOverflow Retry with Exponential Backoff',
      description: 'Pasted suspending retry helper',
      code: `// Pasted Kotlin suspend retry function
suspend fun <T> retryIO(times: Int = 3, initialDelay: Long = 100, block: suspend () -> T): T {
    var currentDelay = initialDelay
    repeat(times - 1) {
        try { return block() }
        catch (e: Exception) { kotlinx.coroutines.delay(currentDelay); currentDelay *= 2 }
    }
    return block()
}`
    }
  },
  {
    id: 'sql',
    name: 'SQL',
    category: 'Data & Scripting',
    extension: '.sql',
    defaultFilename: 'schema.sql',
    color: '#e38c00',
    badgeBg: 'bg-amber-500/20 text-amber-300',
    badgeBorder: 'border-amber-500/30',
    starterCode: `CREATE TABLE audit_records (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);`,
    aiSnippet: {
      label: 'Recursive CTE for Hash Chain Audit',
      description: 'Copilot generated chain traversal query',
      code: `WITH RECURSIVE ChainAudit AS (
    SELECT sequence, prev_hash, current_hash, 1 as depth
    FROM provenance_links
    WHERE prev_hash = REPEAT('0', 64)
    UNION ALL
    SELECT p.sequence, p.prev_hash, p.current_hash, c.depth + 1
    FROM provenance_links p
    JOIN ChainAudit c ON p.prev_hash = c.current_hash
)
SELECT * FROM ChainAudit ORDER BY sequence ASC;`
    },
    pasteSnippet: {
      label: 'StackOverflow Percentile Aggregation',
      description: 'Pasted SQL window function for statistics',
      code: `-- Pasted percentile calculation window query
SELECT 
    file_path,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY line_count) as median_chunk,
    COUNT(*) as total_events
FROM provenance_events
GROUP BY file_path;`
    }
  },
  {
    id: 'shell',
    name: 'Shell / Bash',
    category: 'Data & Scripting',
    extension: '.sh',
    defaultFilename: 'verify.sh',
    color: '#89e051',
    badgeBg: 'bg-lime-500/20 text-lime-300',
    badgeBorder: 'border-lime-500/30',
    starterCode: `#!/usr/bin/env bash
set -euo pipefail

echo "Shell script environment ready."`,
    aiSnippet: {
      label: 'CI Gatekeeper Pre-Push Script',
      description: 'Copilot generated Git pre-push hook',
      code: `#!/usr/bin/env bash
# Git pre-push CI policy gate
MAX_AI=50
ACTUAL_AI=$(jq -r '.summary.percentages.ai' .provenance-bundle.json 2>/dev/null || echo "0")

if (( $(echo "$ACTUAL_AI > $MAX_AI" | bc -l) )); then
    echo "❌ PUSH BLOCKED: AI code percentage ($ACTUAL_AI%) exceeds policy ($MAX_AI%)"
    exit 1
fi
echo "✅ Provenance policy passed: $ACTUAL_AI% AI"
exit 0`
    },
    pasteSnippet: {
      label: 'StackOverflow Colors & Trap Exit',
      description: 'Pasted bash formatting and cleanup trap',
      code: `# Pasted bash boilerplate with colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
NC='\\033[0m'
trap 'echo -e "\${RED}Interrupted!\${NC}"; exit 1' INT TERM`
    }
  },
  {
    id: 'html',
    name: 'HTML',
    category: 'Web',
    extension: '.html',
    defaultFilename: 'index.html',
    color: '#e34c26',
    badgeBg: 'bg-orange-500/20 text-orange-300',
    badgeBorder: 'border-orange-500/30',
    starterCode: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>App</title>
</head>
<body>
  <h1>Provenance Tracker</h1>
</body>
</html>`,
    aiSnippet: {
      label: 'Accessible Provenance Table',
      description: 'Copilot generated responsive audit table',
      code: `<figure class="audit-wrapper">
  <table aria-describedby="provenance-caption">
    <caption id="provenance-caption">Cryptographic File Provenance Table</caption>
    <thead>
      <tr>
        <th scope="col">File Name</th>
        <th scope="col">Typed %</th>
        <th scope="col">AI %</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>src/main.py</td><td>70%</td><td>30%</td></tr>
    </tbody>
  </table>
</figure>`
    },
    pasteSnippet: {
      label: 'StackOverflow Viewport Boilerplate',
      description: 'Pasted meta tags for mobile responsiveness',
      code: `<!-- Pasted mobile viewport snippet -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
<meta name="color-scheme" content="dark light">`
    }
  },
  {
    id: 'css',
    name: 'CSS',
    category: 'Web',
    extension: '.css',
    defaultFilename: 'styles.css',
    color: '#563d7c',
    badgeBg: 'bg-violet-500/20 text-violet-300',
    badgeBorder: 'border-violet-500/30',
    starterCode: `:root {
  --primary: #3b82f6;
  --bg-color: #0f172a;
}

body {
  margin: 0;
  padding: 0;
}`,
    aiSnippet: {
      label: 'Modern CSS Grid Bento Layout',
      description: 'Copilot generated responsive telemetry grid',
      code: `.provenance-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1.5rem;
  padding: 1rem;
}

@container (min-width: 600px) {
  .hero-metric {
    grid-column: span 2;
  }
}`
    },
    pasteSnippet: {
      label: 'StackOverflow Modern Reset',
      description: 'Pasted modern CSS box-sizing reset',
      code: `/* Pasted Modern CSS Reset */
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}`
    }
  }
];

export function getLanguageById(id: string): LanguageDefinition {
  return SUPPORTED_LANGUAGES.find((l) => l.id === id) || SUPPORTED_LANGUAGES[0];
}

export function detectLanguageFromPath(path: string): LanguageDefinition {
  const ext = '.' + path.split('.').pop()?.toLowerCase();
  const found = SUPPORTED_LANGUAGES.find((l) => l.extension === ext);
  return found || SUPPORTED_LANGUAGES[1]; // default TypeScript
}

export function findLanguageByKeyword(keyword: string): LanguageDefinition | undefined {
  const lower = keyword.toLowerCase();
  if (lower.includes('python')) return getLanguageById('python');
  if (lower.includes('typescript')) return getLanguageById('typescript');
  if (lower.includes('javascript') || lower.includes('node')) return getLanguageById('javascript');
  if (lower.includes('c++') || lower.includes('cpp')) return getLanguageById('cpp');
  if (lower.includes('rust')) return getLanguageById('rust');
  if (lower.includes('go')) return getLanguageById('go');
  if (lower.includes('java') && !lower.includes('script')) return getLanguageById('java');
  if (lower.includes('sql')) return getLanguageById('sql');
  if (lower.includes('html')) return getLanguageById('html');
  if (lower.includes('css')) return getLanguageById('css');
  return undefined;
}

